spring.application.name=notes-api
spring.datasource.url=***
spring.datasource.username=***
spring.datasource.password=***
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.envers.auto_register_listeners=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.tool.schema=DEBUG
