spring.application.name=notes-api
spring.datasource.url=***
spring.datasource.username=***
spring.datasource.password=***
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.envers.auto_register_listeners=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.tool.schema=DEBUG
security.jwt.expiration-minutes=3600
security.jwt.secret-key=***
security.rate.capacity=5
security.rate.refill-minutes=1
